from src.automata.dsa import DSA


def f_b_dsa(parameters):
    return DSA(
        2,
        {
            "",
            "B",
        },
        {
            (0, ""): 0,
            (0, "B"): 0,
            (1, ""): 1,
            (1, "B"): 0,
        },
        [({1}, {0})],
        initial_state=1,
        epsilon=parameters["epsilon"],
    )


def f_b_g_not_h_dsa(params):
    return DSA(
        3,
        {"", "B", "H", "BH"},
        {
            (0, ""): 0,
            (0, "B"): 0,
            (0, "H"): 2,
            (0, "BH"): 2,
            (1, ""): 1,
            (1, "B"): 0,
            (1, "H"): 2,
            (1, "BH"): 2,
            (2, ""): 2,
            (2, "B"): 2,
            (2, "H"): 2,
            (2, "BH"): 2,
        },
        [({1, 2}, {0})],
        initial_state=1,
        epsilon=params["epsilon"],
    )


def fg_e_g_not_h_dsa(params):
    return DSA(
        3,
        {"", "E", "H", "EH"},
        {
            (0, ""): 0,
            (0, "E"): 1,
            (0, "H"): 2,
            (0, "EH"): 2,
            (1, ""): 0,
            (1, "E"): 1,
            (1, "H"): 2,
            (1, "EH"): 2,
            (2, ""): 2,
            (2, "E"): 2,
            (2, "H"): 2,
            (2, "EH"): 2,
        },
        [
            ({0, 2}, set()),
            ({0, 2}, {1}),
        ],
        initial_state=0,
        epsilon=params["epsilon"],
    )


def gf_b_dsa(params):
    return DSA(
        2,
        {"", "B"},
        {
            (0, ""): 0,
            (0, "B"): 1,
            (1, ""): 0,
            (1, "B"): 1,
        },
        [({0}, {1})],
        initial_state=1,
        epsilon=params["epsilon"],
    )


def gfa_gfb_g_not_h_dsa(parameters):
    return DSA(
        6,
        {
            "",
            "A",
            "B",
            "H",
            "AB",
            "AH",
            "BH",
            "ABH",
        },
        {
            (0, ""): 2,
            (0, "A"): 1,
            (0, "B"): 2,
            (0, "H"): 3,
            (0, "AB"): 0,
            (0, "AH"): 3,
            (0, "BH"): 3,
            (0, "ABH"): 3,
            (1, ""): 5,
            (1, "A"): 4,
            (1, "B"): 2,
            (1, "H"): 3,
            (1, "AB"): 0,
            (1, "AH"): 3,
            (1, "BH"): 3,
            (1, "ABH"): 3,
            (2, ""): 2,
            (2, "A"): 1,
            (2, "B"): 2,
            (2, "H"): 3,
            (2, "AB"): 0,
            (2, "AH"): 3,
            (2, "BH"): 3,
            (2, "ABH"): 3,
            (3, ""): 3,
            (3, "A"): 3,
            (3, "B"): 3,
            (3, "H"): 3,
            (3, "AB"): 3,
            (3, "AH"): 3,
            (3, "BH"): 3,
            (3, "ABH"): 3,
            (4, ""): 5,
            (4, "A"): 4,
            (4, "B"): 0,
            (4, "H"): 3,
            (4, "AB"): 0,
            (4, "AH"): 3,
            (4, "BH"): 3,
            (4, "ABH"): 3,
            (5, ""): 5,
            (5, "A"): 4,
            (5, "B"): 2,
            (5, "H"): 3,
            (5, "AB"): 0,
            (5, "AH"): 3,
            (5, "BH"): 3,
            (5, "ABH"): 3,
        },
        [
            ({2, 3, 4, 5}, {0, 1}),
        ],
        initial_state=0,
        epsilon=parameters["epsilon"],
        m=parameters["m"] if parameters.get("m") is not None else 0,
        sink_penalty=parameters["sink_penalty"]
        if parameters.get("sink_penalty") is not None
        else parameters["epsilon"],
    )


def gf_a_or_b_then_fg_not_e_dsa(params):
    return DSA(
        7,
        {
            "",
            "A",
            "B",
            "E",
            "AB",
            "AE",
            "BE",
            "ABE",
        },
        {
            (0, ""): 2,
            (0, "A"): 2,
            (0, "B"): 2,
            (0, "E"): 1,
            (0, "AB"): 2,
            (0, "AE"): 0,
            (0, "BE"): 0,
            (0, "ABE"): 0,
            (1, ""): 5,
            (1, "A"): 6,
            (1, "B"): 6,
            (1, "E"): 5,
            (1, "AB"): 6,
            (1, "AE"): 0,
            (1, "BE"): 0,
            (1, "ABE"): 0,
            (2, ""): 4,
            (2, "A"): 4,
            (2, "B"): 4,
            (2, "E"): 3,
            (2, "AB"): 4,
            (2, "AE"): 0,
            (2, "BE"): 0,
            (2, "ABE"): 0,
            (3, ""): 5,
            (3, "A"): 6,
            (3, "B"): 6,
            (3, "E"): 5,
            (3, "AB"): 6,
            (3, "AE"): 0,
            (3, "BE"): 0,
            (3, "ABE"): 0,
            (4, ""): 4,
            (4, "A"): 4,
            (4, "B"): 4,
            (4, "E"): 3,
            (4, "AB"): 4,
            (4, "AE"): 0,
            (4, "BE"): 0,
            (4, "ABE"): 0,
            (5, ""): 5,
            (5, "A"): 6,
            (5, "B"): 6,
            (5, "E"): 5,
            (5, "AB"): 6,
            (5, "AE"): 0,
            (5, "BE"): 0,
            (5, "ABE"): 0,
            (6, ""): 4,
            (6, "A"): 4,
            (6, "B"): 4,
            (6, "E"): 3,
            (6, "AB"): 4,
            (6, "AE"): 0,
            (6, "BE"): 0,
            (6, "ABE"): 0,
        },
        [
            ({0, 3, 6}, set()),
            ({0, 1, 2, 3, 6}, {4, 5}),
        ],
        initial_state=0,
        epsilon=params["epsilon"],
    )


def f_c_f_d_gfa_gfb_g_not_h_dsa(params):
    return DSA(
        6,
        {
            "",
            "A",
            "B",
            "C",
            "D",
            "H",
        },
        {
            (0, ""): 0,
            (0, "A"): 0,
            (0, "B"): 0,
            (0, "C"): 2,
            (0, "D"): 0,
            (0, "H"): 5,
            (1, ""): 3,
            (1, "A"): 3,
            (1, "B"): 4,
            (1, "C"): 3,
            (1, "D"): 3,
            (1, "H"): 5,
            (2, ""): 2,
            (2, "A"): 2,
            (2, "B"): 2,
            (2, "C"): 2,
            (2, "D"): 1,
            (2, "H"): 5,
            (3, ""): 3,
            (3, "A"): 3,
            (3, "B"): 4,
            (3, "C"): 3,
            (3, "D"): 3,
            (3, "H"): 5,
            (4, ""): 4,
            (4, "A"): 1,
            (4, "B"): 4,
            (4, "C"): 4,
            (4, "D"): 4,
            (4, "H"): 5,
            (5, ""): 5,
            (5, "A"): 5,
            (5, "B"): 5,
            (5, "C"): 5,
            (5, "D"): 5,
            (5, "H"): 5,
        },
        [
            ({0, 2, 3, 4, 5}, {1}),
        ],
        initial_state=0,
        epsilon=params["epsilon"],
        m=params["m"] if params.get("m") is not None else 0,
        sink_penalty=params["sink_penalty"]
        if params.get("sink_penalty") is not None
        else 0,
    )


def gfa_then_gf_b_or_c_dsa(parameters):
    return DSA(
        3,
        {"", "A", "B", "C", "AB", "AC", "BC", "ABC"},
        {
            (0, ""): 2,
            (0, "A"): 1,
            (0, "B"): 0,
            (0, "C"): 0,
            (0, "AB"): 0,
            (0, "AC"): 0,
            (0, "BC"): 0,
            (0, "ABC"): 0,
            (1, ""): 2,
            (1, "A"): 1,
            (1, "B"): 0,
            (1, "C"): 0,
            (1, "AB"): 0,
            (1, "AC"): 0,
            (1, "BC"): 0,
            (1, "ABC"): 0,
            (2, ""): 2,
            (2, "A"): 1,
            (2, "B"): 0,
            (2, "C"): 0,
            (2, "AB"): 0,
            (2, "AC"): 0,
            (2, "BC"): 0,
            (2, "ABC"): 0,
        },
        [({1}, {0})],
        initial_state=0,
        epsilon=parameters["epsilon"],
        m=parameters["m"] if parameters.get("m") is not None else 0,
    )
